### ISSUE TITLE
hi im interested in this i have tried 

### ISSUE THREAD

**Issue by ciindyprem** [makevoid/ethereum-geth-dev#1]
hi im interested in this i have tried pulling.....but no luck can u help

**Comment by ciindyprem** [comment]
OK it worked..... fixed my problem the blockchain is downloading THANK YOU 
I cd the location of geth and cloned it from there reboot and viola

**Comment by makevoid** [comment]
no problem, glad you like the project/container/script, I'm closing the issue. Have fun with Ethereum!
